# -*- coding: utf-8 -*-
"""RAGHTMLtest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_A1xhzLF_i9xy-OB9jjWtH1s-pMtwzQS
"""

import os
from openai import OpenAI, AuthenticationError
from dotenv import load_dotenv
from bs4 import BeautifulSoup # using beautiful soup to extract the text from an html, at least locally
import chromadb
from chromadb.utils import embedding_functions



def create_client(api_key):
    try:
        client = OpenAI(api_key=api_key)
        client.models.list()
        return client
    except AuthenticationError:
        print("Invalid API")
    return None



load_dotenv()
chroma_client = chromadb.Client()

# load and get api key from environment
# also making a chroma client
api_key = os.environ["OPENAI_KEY"]

openai_ef = embedding_functions.OpenAIEmbeddingFunction(
    api_key = api_key,
    model_name = "text-embedding-3-small"
)
# configuring embeddings for OpenAI with chromadb

client = create_client(api_key)

database = chroma_client.get_or_create_collection(name="RAG_Work_test", embedding_function=openai_ef)
# making the database, it'll make one if there isn't one already

# opening the html from assignment 1 and using soup to extract the text from it
with open("index.html", "r") as f:
    content = f.read()

soup = BeautifulSoup(content, "html.parser")
htm_txt = soup.get_text(strip=True)

database.add(
    documents=htm_txt,
    metadatas=[{"source": "index.html"}],
    ids=["id_001"]
)

# was initially gonna have this be above with the other function but it conflicts with load_dotenv
# this is the same as test.py


def get_context(query):
    res = database.query(
        query_texts=[query],
        n_results=3,
    )
    # querying the database with relevant info then extracting
    if res["documents"] and res["documents"][0]:
        context = "\n\n".join(res["documents"][0])
        return context
    return ""









def chat(user_input):
    context = get_context(user_input)

    msg = [{
        "role": "developer", "content": "Talk like an assistant, use the context to answer the question."
    }]

    if context:
        msg.append({
            "role":"user",
            "content": f"Context from the HTML document:\n{context}\n\nBased on this context, please answer: {user_input}"
        })
    else:
        msg.append({
             "role":"user",
            "content":user_input
        })



    comp = client.chat.completions.create(
    model="gpt-4",
    messages=msg,
)
    response = comp.choices[0].message.content
    return response



# simple loop that should make so you can keep talking to it
print("Welcome to the RAGWork test, currently the only the thing in the database is\n")
print("The html from Assignment 1, this is a local html, be sure to type exit when you want to quit!")

while(True):
    user_input = input("You: ")
    if user_input.lower() == 'exit':
        print("Rag: Goodbye!")
        break
    assistant_rply = chat(user_input)
    print("RAG: ", assistant_rply, "\nAnything else needed? ")
